version: "3.3"

services:
  ELASTICMASTER:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: ELASTICMASTER
    volumes:
      - ./certs:/usr/share/elasticsearch/config/certs
      - ./elasticsearch/ELASTICMASTER/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      #- ./elasticsearch/ELASTICMASTER/data:/usr/share/elasticsearch/data
      - ./elasticsearch/ELASTICMASTER/snapshots:/usr/share/elasticsearch/snapshots
    ports:
      - ${ES_PORT}:9200
      - ${ES_INTERNAL_PORT}:9300
    environment:
      ES_JAVA_OPTS: -Xms2g -Xmx2g
      CLUSTER_NAME: ${CLUSTER_NAME:-}
      ES_PORT: ${ES_PORT:-}
      LICENSE: ${LICENSE:-}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      SIEM:

  ELASTICSLAVE:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: ELASTICSLAVE
    volumes:
      - ./certs:/usr/share/elasticsearch/config/certs
      - ./elasticsearch/ELASTICSLAVE/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      #- ./elasticsearch/ELASTICSLAVE/data:/usr/share/elasticsearch/data
      - ./elasticsearch/ELASTICSLAVE/snapshots:/usr/share/elasticsearch/snapshots
    environment:
      ES_JAVA_OPTS: -Xms2g -Xmx2g
      CLUSTER_NAME: ${CLUSTER_NAME:-}
      ES_PORT: 9201
      LICENSE: ${LICENSE:-}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      SIEM:

  KIBANA:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: KIBANA
    volumes:
      - ./certs:/usr/share/kibana/config/certs
      - ./kibana/KIBANA/kibana.yml:/usr/share/kibana/config/kibana.yml
     # - ./kibana/KIBANA/data:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      ES_JAVA_OPTS: -Xms2g -Xmx2g
      KIBANA_PORT: ${KIBANA_PORT:-}
      KIBANA_USER: ${KIBANA_USER:-}
      KIBANA_PASSWORD: ${KIBANA_PASSWORD:-}
      KIBANA_ENCKEY: ${KIBANA_ENCKEY:-}
    restart: unless-stopped
    networks:
      SIEM:
#
#  METRICBEAT:
#    image: docker.elastic.co/beats/metricbeat:${STACK_VERSION}
#    container_name: METRICBEAT
#    volumes:
#      - ./certs:/usr/share/metricbeat/config/certs
#      - ./metricbeat/METRICBEAT/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
#    restart: unless-stopped
#    networks:
#      SIEM:
#
  LOGSTASH:
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    container_name: LOGSTASH
    volumes:
      - ./logstash/LOGSTASH/PIPELINES/:/usr/share/logstash/pipeline/
      - ./logstash/LOGSTASH/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - 5044:5044
      - 9600:9600
    environment:
      LS_JAVA_OPTS: -Xms1g -Xmx2g
    restart: unless-stopped
    networks:
      SIEM:

networks:
  SIEM:
    driver: bridge
